### ISSUE TITLE
Running example site doesn't seem to work

### ISSUE THREAD

**Issue by pganssle** [dzello/reveal-hugo#2]
I tried building the example site as mentioned in the README.md and it is throwing some sort of panic:

```bash
$ git clone https://github.com/dzello/reveal-hugo.git
$ cd reveal-hugo
$ hugo server -s exampleSite -d ../public --themesDir '../' --theme '.'
panic: AllThemes not set

... huge error message
```

Here is the full error message that was truncated from above:
<details>

```
panic: AllThemes not set
goroutine 1 [running]:
github.com/gohugoio/hugo/hugolib/filesystems.createThemesOverlayFs(0xc4201228c0, 0x0, 0xc420176fc8, 0x562f2b36c95a, 0x30, 0x562f2c2f9aa0, 0x1, 0xc4202320f0)
	/build/hugo/src/src/github.com/gohugoio/hugo/hugolib/filesystems/basefs.go:572 +0x317
github.com/gohugoio/hugo/hugolib/filesystems.(*sourceFilesystemsBuilder).Build(0xc420493e40, 0xc4202320f0, 0xc4204d00c0, 0x3c)
	/build/hugo/src/src/github.com/gohugoio/hugo/hugolib/filesystems/basefs.go:258 +0x2f0
github.com/gohugoio/hugo/hugolib/filesystems.NewBase(0xc4201228c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x10)
	/build/hugo/src/src/github.com/gohugoio/hugo/hugolib/filesystems/basefs.go:232 +0x7e7
github.com/gohugoio/hugo/helpers.NewPathSpecWithBaseBaseFsProvided(0xc420493940, 0x562f2c36bc20, 0xc4204c38f0, 0x0, 0xc4202692a0, 0x20, 0x20)
	/build/hugo/src/src/github.com/gohugoio/hugo/helpers/pathspec.go:59 +0xa1
github.com/gohugoio/hugo/helpers.NewPathSpec(0xc420493940, 0x562f2c36bc20, 0xc4204c38f0, 0xc4202692a0, 0x0, 0x562f2c8480a0)
	/build/hugo/src/src/github.com/gohugoio/hugo/helpers/pathspec.go:41 +0x4a
github.com/gohugoio/hugo/deps.New(0xc4204b0000, 0xc420493940, 0xc4204c38f0, 0x562f2c36bd40, 0xc420259860, 0x562f2c35c7e0, 0x0, 0xc4202692a0, 0x562f2c35c760, 0xc420269280, ...)
	/build/hugo/src/src/github.com/gohugoio/hugo/deps/deps.go:126 +0xb2
github.com/gohugoio/hugo/hugolib.applyDepsIfNeeded(0xc4204b0000, 0xc420493940, 0xc4204c38f0, 0x562f2c36bd40, 0xc420259860, 0x562f2c35c7e0, 0x0, 0xc4202692a0, 0x562f2c35c760, 0xc420269280, ...)
	/build/hugo/src/src/github.com/gohugoio/hugo/hugolib/hugo_sites.go:190 +0x323
github.com/gohugoio/hugo/hugolib.newHugoSites(0xc4204b0000, 0xc420493940, 0x0, 0x562f2c36bd40, 0xc420259860, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/build/hugo/src/src/github.com/gohugoio/hugo/hugolib/hugo_sites.go:134 +0x24f
github.com/gohugoio/hugo/hugolib.NewHugoSites(0xc4204b0000, 0xc420493940, 0x0, 0x562f2c36bd40, 0xc420259860, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/build/hugo/src/src/github.com/gohugoio/hugo/hugolib/hugo_sites.go:227 +0xf7
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig.func3()
	/build/hugo/src/src/github.com/gohugoio/hugo/commands/commandeer.go:203 +0x119
sync.(*Once).Do(0xc4200ba890, 0xc420453968)
	/usr/lib/go/src/sync/once.go:44 +0xc0
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig(0xc4200ba840, 0xc4200b0101, 0xc420092420, 0xc420092480)
	/build/hugo/src/src/github.com/gohugoio/hugo/commands/commandeer.go:188 +0x564
github.com/gohugoio/hugo/commands.newCommandeer(0xc420470101, 0xc4202bc060, 0x562f2c359be0, 0xc420492040, 0xc4204818e0, 0x0, 0x0, 0x0, 0xc4202f8c80, 0x1, ...)
	/build/hugo/src/src/github.com/gohugoio/hugo/commands/commandeer.go:99 +0x118
github.com/gohugoio/hugo/commands.initializeConfig(0x101, 0xc4202bc060, 0x562f2c359be0, 0xc420492040, 0xc4204818e0, 0x0, 0x0, 0x562f2b5020d2)
	/build/hugo/src/src/github.com/gohugoio/hugo/commands/hugo.go:111 +0x78
github.com/gohugoio/hugo/commands.(*serverCmd).server(0xc420492040, 0xc4204b8780, 0xc420215300, 0x0, 0x8, 0x0, 0x0)
	/build/hugo/src/src/github.com/gohugoio/hugo/commands/server.go:229 +0x1d8
github.com/gohugoio/hugo/commands.(*serverCmd).(github.com/gohugoio/hugo/commands.server)-fm(0xc4204b8780, 0xc420215300, 0x0, 0x8, 0x0, 0x0)
	/build/hugo/src/src/github.com/gohugoio/hugo/commands/server.go:83 +0x54
github.com/gohugoio/hugo/vendor/github.com/spf13/cobra.(*Command).execute(0xc4204b8780, 0xc420215200, 0x8, 0x8, 0xc4204b8780, 0xc420215200)
	/build/hugo/src/src/github.com/gohugoio/hugo/vendor/github.com/spf13/cobra/command.go:756 +0x46a
github.com/gohugoio/hugo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4202f8780, 0xc42047f090, 0xc420482280, 0xc420453ee8)
	/build/hugo/src/src/github.com/gohugoio/hugo/vendor/github.com/spf13/cobra/command.go:846 +0x30c
github.com/gohugoio/hugo/commands.Execute(0xc4200ae010, 0x9, 0x9, 0xc420453f78, 0x562f2b35fe0e, 0xc420092058, 0x0)
	/build/hugo/src/src/github.com/gohugoio/hugo/commands/hugo.go:77 +0xc0
main.main()
	/build/hugo/src/src/github.com/gohugoio/hugo/main.go:27 +0x7d
```

</details>

Not sure if the instructions need to be fixed or the configuration or what.

Versions:
```
$ hugo version
Hugo Static Site Generator v0.42.1 linux/amd64 BuildDate: 2018-06-13T20:49:30+0200
```

Using Arch Linux.

**Comment by dzello** [comment]
Thanks the the report! It looks like a bug was introduced in 0.42 where there is an issue with setting a theme on the command line, see more info in [#4851](https://github.com/gohugoio/hugo/issues/4851). 

I've implemented the workaround mentioned in that issue - now specifying the theme and themeDir in the config.toml of the exampleSite instead of on the command line. I think this leads to an easier-to-follow approach regardless of needing to work around the bug, but happy to get your thoughts too.

Let me know if this gets you up and running.
